[workspace]
members = [
  "crates/core",
  "crates/input",
  "crates/overlay",
  "crates/app",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"
rust-version = "1.74"
repository = "https://github.com/dshepstone/keyoverlay"

[patch.crates-io]
egui-wgpu = { path = "vendor/egui-wgpu-0.27.2" }
